In [356]:
import numpy as np

np.set_printoptions(suppress = True, linewidth = 100, precision = 2)

In [357]:
raw_data_np = np.genfromtxt('loan-data.csv', delimiter=";", autostrip = True, skip_header=1)
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [358]:
np.isnan(raw_data_np).sum()

88005

In [359]:
temporary_fill = np.nanmax(raw_data_np) + 1
temporary_fill

68616520.0

In [360]:
temporary_mean = np.nanmean(raw_data_np, axis = 0)
temporary_mean

C:\Users\theot\AppData\Local\Temp\ipykernel_6500\2293217592.py:1: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data_np, axis = 0)


array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [361]:
temporary_stat = np.array([np.nanmax(raw_data_np, axis=0), temporary_mean, np.nanmin(raw_data_np, axis=0)])
temporary_stat

C:\Users\theot\AppData\Local\Temp\ipykernel_6500\3402490975.py:1: RuntimeWarning: All-NaN slice encountered
  temporary_stat = np.array([np.nanmax(raw_data_np, axis=0), temporary_mean, np.nanmin(raw_data_np, axis=0)])


array([[68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ]])

In [362]:
column_string = np.argwhere(np.isnan(temporary_mean)).squeeze()
column_string

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [363]:
column_numeric = np.argwhere(np.isnan(temporary_mean) == False).squeeze()
column_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [364]:
loan_data_string = np.genfromtxt('loan-data.csv', 
                                 delimiter=";", 
                                 autostrip=True, 
                                 skip_header=1, 
                                 usecols=column_string, 
                                 dtype = str)
loan_data_string

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [365]:
loan_data_numeric = np.genfromtxt('loan-data.csv', 
                                 delimiter=";", 
                                 autostrip=True, 
                                 skip_header=1, 
                                 usecols=column_numeric,
                                 filling_values=temporary_fill)
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [366]:
header_full = np.genfromtxt('loan-data.csv',
                            delimiter=";",
                            autostrip=True,
                            skip_footer=np.shape(raw_data_np)[0],
                            dtype = str)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [367]:
header_string, header_numeric = header_full[column_string], header_full[column_numeric]

In [368]:
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [369]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [370]:
header_string[0] = 'issue_date'

In [371]:
loan_data_string[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [372]:
np.unique(loan_data_string[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [373]:
loan_data_string[:,0] = np.chararray.strip(loan_data_string[:,0], '-15')

In [374]:
loan_data_string[:,0]

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

In [375]:
np.unique(loan_data_string[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [376]:
months = ['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

In [377]:
for i in range(len(months)):
    loan_data_string[:,0] = np.where(loan_data_string[:,0] == months[i],
                                     i,
                                     loan_data_string[:,0])
np.unique(loan_data_string[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [378]:
header_string[1]

'loan_status'

In [379]:
loan_data_string[:,1]

array(['Current', 'Current', 'Current', ..., 'Current', 'Current', 'Current'], dtype='<U69')

In [380]:
np.unique(loan_data_string[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [381]:
bad = np.array(['', 'Current', 'Default', 'Late (31-120 days)'])

In [382]:
loan_data_string[:,1] = np.where(np.isin(loan_data_string[:,1], bad), 0, 1)
np.unique(loan_data_string[:,1])

array(['0', '1'], dtype='<U69')

In [383]:
np.unique(loan_data_string[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [384]:
loan_data_string[:,2] = np.chararray.strip(loan_data_string[:,2], ' months')

In [385]:
loan_data_string[:,2] = np.where(loan_data_string[:,2] == '', 60, loan_data_string[:,2])
np.unique(loan_data_string[:,2])

array(['36', '60'], dtype='<U69')

In [386]:
np.unique(loan_data_string[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [387]:
loan_data_string = np.delete(loan_data_string, 3, axis = 1)
header_string = np.delete(header_string, 3)

In [388]:
loan_data_string[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [389]:
np.unique(loan_data_string[:,3])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [390]:
loan_data_string[:,3] = np.where(loan_data_string[:,3] == '', 'H1', loan_data_string[:,3])

In [391]:
for i in range(len(np.unique(loan_data_string[:,3]))):
    loan_data_string[:,3] = np.where(loan_data_string[:,3] == np.unique(loan_data_string[:,3])[i],
                                    i+1,
                                    loan_data_string[:,3])
np.unique(loan_data_string[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [392]:
np.unique(loan_data_string[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [393]:
loan_data_string[:,4] = np.where((loan_data_string[:,4] == '') | (loan_data_string[:,4] == 'Not Verified'), 0, 1)
np.unique(loan_data_string[:,4])

array(['0', '1'], dtype='<U69')

In [394]:
np.unique(loan_data_string[:,5])

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=12606806',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=13026045',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=1312426', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8138291',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8214572',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=849994'], dtype='<U69')

In [395]:
loan_data_string = np.delete(loan_data_string, 5, axis = 1)
header_string = np.delete(header_string, 5)

In [396]:
loan_data_string[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [397]:
np.unique(loan_data_string[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [398]:
header_string[5] = 'address_state'

In [399]:
name, count = np.unique(loan_data_string[:,5], return_counts = True)
count_index = np.argsort(-count)
name[count_index], count[count_index]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [400]:
loan_data_string[:,5] = np.where(loan_data_string[:,5] == '', 0, loan_data_string[:,5])

In [401]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [402]:
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_west), 1, loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_south), 2, loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_midwest), 3, loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_east), 4, loan_data_string[:,5])

In [403]:
def checkpoint(filename, header_checkpoint, data_checkpoint):
    np.savez(filename, header = header_checkpoint, data = data_checkpoint)
    checkpoint_var = np.load(filename + '.npz')
    return checkpoint_var

In [404]:
loan_data_string = loan_data_string.astype(np.int32)

In [405]:
checkpoint_string = checkpoint('Checkpoint-String', header_string, loan_data_string)
checkpoint_string['header']

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'address_state'],
      dtype='<U19')

In [406]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [407]:
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [408]:
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2] == temporary_fill,
                                  temporary_stat[0, column_numeric[2]],
                                  loan_data_numeric[:,2])

In [409]:
for i in [1,3,4,5]:
    loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i] == temporary_fill,
                                      temporary_stat[2, column_numeric[i]],
                                      loan_data_numeric[:,i])

In [410]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [411]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,        6.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,        6.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,        6.  ,       31.42,     2185.64],
       [46154151.  ,     1000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,        6.  ,      309.97,      301.9 ]])

In [412]:
EUR_USD = np.genfromtxt('EUR-USD.csv', delimiter=",", autostrip=True, skip_header=1, usecols=3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [413]:
exchange_rate = loan_data_string[:,0]

for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                             EUR_USD[i-1],
                             exchange_rate)
exchange_rate = np.where(exchange_rate == 0,
                        np.mean(EUR_USD),
                        exchange_rate)
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [414]:
header_numeric = np.concatenate((header_numeric, np.array(['Exchange_rate'])))

In [415]:
exchange_rate = np.reshape(exchange_rate, (10000,1))

In [416]:
loan_data_numeric = np.hstack((loan_data_numeric, exchange_rate))

In [417]:
column_dollar = [1,2,4,5]

In [418]:
for i in column_dollar:
    loan_data_numeric = np.hstack((loan_data_numeric, np.reshape(loan_data_numeric[:,i] / loan_data_numeric[:,6], (10000,1))))

In [419]:
header_additional = np.array([column_name + "_EUR" for column_name in header_numeric[column_dollar]])
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [420]:
header_numeric = np.concatenate((header_numeric, header_additional))

In [421]:
header_numeric[column_dollar] = np.array([column_name + "_USD" for column_name in header_numeric[column_dollar]])
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'Exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [422]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [423]:
header_numeric = header_numeric[columns_index_order]

In [424]:
loan_data_numeric = loan_data_numeric[:,columns_index_order]

In [425]:
checkpoint_numeric = checkpoint('Checkpoint-Numeric', header_numeric, loan_data_numeric)

In [426]:
header_full = np.concatenate((checkpoint_string['header'], checkpoint_numeric['header']))

In [427]:
loan_data = np.hstack((checkpoint_string['data'], checkpoint_numeric['data']))

In [428]:
loan_data

array([[   5.  ,    0.  ,   36.  , ..., 9452.96, 8624.69,    1.1 ],
       [   0.  ,    0.  ,   36.  , ..., 4679.7 , 4232.39,    1.11],
       [   9.  ,    0.  ,   36.  , ..., 1969.83, 1750.04,    1.13],
       ...,
       [   6.  ,    0.  ,   36.  , ..., 2185.64, 1947.47,    1.12],
       [   4.  ,    0.  ,   36.  , ..., 3199.4 , 2878.63,    1.11],
       [  12.  ,    0.  ,   36.  , ...,  301.9 ,  276.11,    1.09]])

In [430]:
np.isnan(loan_data).sum()

0

In [431]:
loan_data = np.vstack((header_full, loan_data))

In [432]:
np.savetxt('loan-data-preprocessed.csv', loan_data, delimiter=",", fmt="%s")

In [433]:
loan_data

array([['issue_date', 'loan_status', 'term', ..., 'total_pymnt_USD', 'total_pymnt_EUR',
        'Exchange_rate'],
       ['5.0', '0.0', '36.0', ..., '9452.96', '8624.69180362759', '1.0960345268249512'],
       ['0.0', '0.0', '36.0', ..., '4679.7', '4232.392434286058', '1.1056866943836212'],
       ...,
       ['6.0', '0.0', '36.0', ..., '2185.64', '1947.4707692203106', '1.122296690940857'],
       ['4.0', '0.0', '36.0', ..., '3199.4', '2878.628147743589', '1.1114321947097778'],
       ['12.0', '0.0', '36.0', ..., '301.9', '276.11169400031923', '1.093398094177246']],
      dtype='<U32')